language: node_js
node_js:
  - "stable"
dist: trusty
sudo: false
cache:
  directories:
    - "$HOME/.npm"
    - "node_modules"
stages:
  - name: predeploy
  - name: deploy

before_script:
  - yarn install

jobs:
  include:
    - stage: predeploy
      script: yarn predeploy
    - stage: deploy
      script: yarn deploy
